name: Deploy to Staging

# トリガー：developブランチにプッシュされた時に実行
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub上のサーバーに、リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. GitHub上のサーバーに、SSHキーを設定
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. 接続先のVPSサーバーを、既知のホストとして登録
      - name: Add remote host to known_hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # 4. VPSサーバーにSSH接続して、デプロイコマンドをまとめて実行
      - name: Deploy to Staging Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd /var/www/staging-app &&
            git pull origin develop &&
            source /home/${{ secrets.SSH_USER }}/.nvm/nvm.sh &&
            npm install &&
            npm run build &&
            pm2 reload stg-sho-dev-app
          '
