name: Deploy to Production

# トリガー：手動実行
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # mainブランチのコードをチェックアウトする
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main # ← developではなくmainブランチを指定

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote host to known_hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # 本番サーバーにデプロイする
      - name: Deploy to Production Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd /var/www/sho-dev-app &&      # ← 本番用のディレクトリ
            git pull origin main &&        # ← mainブランチをプル
            source /home/${{ secrets.SSH_USER }}/.nvm/nvm.sh &&
            npm install &&
            npm run build &&
            pm2 reload sho-dev-app         # ← 本番用のプロセスをリロード
          '
